version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://mycandidate:mycandidate_password@db:5432/mycandidate_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - mycandidate-network

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=mycandidate_db
      - POSTGRES_USER=mycandidate
      - POSTGRES_PASSWORD=mycandidate_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mycandidate-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mycandidate-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - mycandidate-network

volumes:
  postgres_data:
  redis_data:

networks:
  mycandidate-network:
    driver: bridge
